// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteRecipe(arg1) {
  return window['go']['backend']['Api']['DeleteRecipe'](arg1);
}

export function GetAllRecipes() {
  return window['go']['backend']['Api']['GetAllRecipes']();
}

export function GetRecipe(arg1) {
  return window['go']['backend']['Api']['GetRecipe'](arg1);
}

export function SaveRecipe(arg1) {
  return window['go']['backend']['Api']['SaveRecipe'](arg1);
}

export function SwapIngredients(arg1, arg2) {
  return window['go']['backend']['Api']['SwapIngredients'](arg1, arg2);
}

export function TestFunc() {
  return window['go']['backend']['Api']['TestFunc']();
}
