// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {recipe} from '../models';

export function DeleteRecipe(arg1:recipe.Recipe):Promise<void>;

export function GetAllRecipes():Promise<Array<recipe.Recipe>>;

export function GetRecipe(arg1:number):Promise<recipe.Recipe>;

export function SaveRecipe(arg1:recipe.Recipe):Promise<void>;

export function SwapIngredients(arg1:recipe.Recipe,arg2:Array<number>):Promise<recipe.Recipe>;

export function TestFunc():Promise<string|string>;
